<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lords" name="NewUserRegistration" tests="2" failures="2" timestamp="5 Nov 2019 11:35:01 GMT" time="16.207" errors="0">
  <testcase name="register" time="0.013" classname="com.DataDriven.NewTours_NewUserRegistration">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.DataDriven.NewTours_NewUserRegistration.register(NewTours_NewUserRegistration.java:47)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- register -->
  <testcase name="newUserRegistration" time="1.181" classname="com.DataDriven.NewTours_NewUserRegistration">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.DataDriven.NewTours_NewUserRegistration.newUserRegistration(NewTours_NewUserRegistration.java:66)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- newUserRegistration -->
</testsuite> <!-- NewUserRegistration -->
